apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-deploy
  namespace: myspace
  labels:
    name: myapp-deploy

spec:
  replicas: 2
  selector: 
    matchLabels:
      name : myapp-pod
  template:
    metadata:
      name: myapp-pod
      namespace: myspace
      labels:
        name: myapp-pod
      
    spec:
      containers:
      - name: app-container
        image: stackupiss/northwind-app:v1 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: DB_HOST
          value: mydb-svc.myspace.svc.cluster.local

---

apiVersion: v1
kind: Service

metadata:
  name: myapp-svc
  namespace: myspace
  labels:
    name: myapp-svc

spec: 
  type: LoadBalancer
  selector:
    name: myapp-pod
  ports:
  - port: 80
    targetPort: 3000

