apiVersion: v1
kind: Pod
metadata:
  name: mydb-pod
  namespace: myspace
  labels:
    name: mydb-pod
    project: northwind
spec:
  containers:
    - name: mydb
      image: stackupiss/northwind-db:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
    - name: myapp
      image: stackupiss/northwind-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: DB_HOST
          value: localhost