apiVersion: v1
kind: ServiceAccount

metadata: 
  name: webui-admin-crb
  namespace: myspace

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: webui-sa
  namespace: myspace

roleRef: 
  apiGroup: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  name: cluster-admin

subjects:
- apiGroup: rbac.authorization.k8s.io/v1beta1
  kind: ServiceAccount
  name: webui-admin